---
- name: Molecule test
  hosts: all
  become: true
  
  tasks:
    - name: Create a test file
      ansible.builtin.file:
        path: /tmp/ansible.file
        state: touch
        mode: '0644'
        modification_time: preserve
        access_time: preserve
