---
dependency:
  name: galaxy
driver:
  name: vagrant
platforms:
  - name: instance
    box:  gentoo-adjust 
    memory: 512
    cpus: 1
    provider_options:
        gui: true
provisioner:
  name: ansible
verifier:
  name: ansible
