name: Molecule CI
on: [push]
jobs:
  Molecule-Converge:
    runs-on: self-hosted
    steps:
      - uses: AutoModality/action-clean@v1
      - uses: actions/checkout@v2
      - run: cd "${{ github.repository }}" && molecule converge
