name: Molecule CI
on: [push]
jobs:
  Molecule-Converge:
    runs-on: self-hosted
    steps:
      - uses: actions/checkout@v2
      - run: pwd && ls -l
      - run: cd "${{ github.repository }}" && molecule converge
